{
  "formatVersion": "0.4",
  "component": {
    "url": "../../fluctsdk/0.0.1-SNAPSHOT1/fluctsdk-0.0.1-SNAPSHOT1.module",
    "group": "jp.s64.kotlin",
    "module": "fluctsdk",
    "version": "0.0.1-SNAPSHOT1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "oxxofrs4yvd4vnuwey55gw3jsa"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "fluctsdk-debug.aar",
          "url": "fluctsdk-android-debug-0.0.1-SNAPSHOT1.aar",
          "size": 28342,
          "sha1": "5a1ce25b89ed1f7f794f6caced1fb24ec86f276f",
          "md5": "fab19b746891df2d08ff166ed65d57ca"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.31"
          }
        }
      ],
      "files": [
        {
          "name": "fluctsdk-debug.aar",
          "url": "fluctsdk-android-debug-0.0.1-SNAPSHOT1.aar",
          "size": 28342,
          "sha1": "5a1ce25b89ed1f7f794f6caced1fb24ec86f276f",
          "md5": "fab19b746891df2d08ff166ed65d57ca"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fluctsdk-metadata/0.0.1-SNAPSHOT1/fluctsdk-metadata-0.0.1-SNAPSHOT1.module",
        "group": "jp.s64.kotlin",
        "module": "fluctsdk-metadata",
        "version": "0.0.1-SNAPSHOT1"
      }
    }
  ]
}
