{
  "formatVersion": "0.4",
  "component": {
    "url": "../../fluctsdk/0.0.1-SNAPSHOT1/fluctsdk-0.0.1-SNAPSHOT1.module",
    "group": "jp.s64.kotlin",
    "module": "fluctsdk",
    "version": "0.0.1-SNAPSHOT1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "oxxofrs4yvd4vnuwey55gw3jsa"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluctsdk.klib",
          "url": "fluctsdk-ios-0.0.1-SNAPSHOT1.klib",
          "size": 37506,
          "sha1": "f95bcaa78ae7f1800f2fc4f90dcf366d872d7a67",
          "md5": "6159cb6ffcb582d938473e2a0828031f"
        },
        {
          "name": "fluctsdk-cinterop-fluctSdkIos.klib",
          "url": "fluctsdk-ios-0.0.1-SNAPSHOT1-cinterop-fluctSdkIos.klib",
          "size": 448198,
          "sha1": "6da653571b376c8999ba1fc9144e7d55fa356c73",
          "md5": "e55e3b2a4309a76f66cd9a485b580192"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fluctsdk-metadata/0.0.1-SNAPSHOT1/fluctsdk-metadata-0.0.1-SNAPSHOT1.module",
        "group": "jp.s64.kotlin",
        "module": "fluctsdk-metadata",
        "version": "0.0.1-SNAPSHOT1"
      }
    }
  ]
}
