# platform :ios, '9.0'

target 'ios' do
  use_frameworks!

  pod 'mpp', :path => '../'
  pod 'FluctSDK-MediationAdapter/UnityAds', '5.1.0'
  pod 'FluctSDK-MediationAdapter/maio', '5.1.0'
  pod 'FluctSDK-MediationAdapter/Tapjoy', '5.1.0'

end
